default:
  outputs:
    dev:
      account: lalyfnc-ez92434
      database: ADAPT_TESTING
      password: Adapt@123
      role: accountadmin
      schema: ADAPT_SCHEMA
      threads: 1
      type: snowflake
      user: sanket
      warehouse: COMPUTE_WH
  target: dev
