default:
  outputs:
    dev:
      account: ao91729.ap-south-1.aws
      database: ADAPT_TESTING
      password: Sap-Hana12
      role: accountadmin
      schema: ADAPT_SCHEMA
      threads: 4
      type: snowflake
      user: rgayatriche12
      warehouse: COMPUTE_WH
  target: dev
